### PR TITLE
Use .trigger(:click) to work around finding elements with before:: css

### PR DESCRIPTION
**Pull request by anitagraham**

### CODE REVIEW

**Comment by anitagraham** [comment]
Still getting errors on 3/4 Travis builds. None *seem* to be associated with these changes.
I see some or all of these errors intermittently on my local system.

**Comment by mhtremblay** [comment]
I would check for these 2 options:
First. I would try to use :
expect(element).to have_css("a selector that will appear after the change of state") 
instead of sleep (theres sleep cause intermittently errors most of time)

and I would try to use :
expect(page.find("#post_category_ids_#{blog_category.id}").checked?).to eq(true) instead of 
expect(page).to have_selector("#post_category_ids_#{blog_category.id}:checked")

Pretty sure that the first solution will solve your problem.

**Comment by parndt** [comment]
I've solved this instead by removing the JS from the tests completely

**Comment by parndt** [comment]
@mhtremblay thanks, your suggestions triggered my brain into fixing the issue completely.

**Comment by mhtremblay** [comment]
np ;-)

**Pull request merged**
