### PR TITLE
Makes it work with Refinery 4.0 and force the refinery version

### PR DESCRIPTION
**Pull request by shanser**
This PR force the versions in order to make the tests pass with Refinery 4.0.0
I suggest that you create a `4-0-stable` branch so we can merge in it.

### CODE REVIEW

**Comment by shanser** [comment]
@parndt / @bricesanchez what do you think of this PR ?
(spoiler :  it will fix a bug we have on a refinerycms4 website 😅 )

**Comment by bricesanchez** [comment]
Hi @shanser ! Thanks for your contribution, which version of jQuery UI do you use? because there was a merged PR who do the opposite of yours? https://github.com/refinery/refinerycms-blog/commit/c1f681496355041d7afe68840ce3a4cad72c22ab

**Comment by shanser** [comment]
Thanks for you reply @bricesanchez.

Yes I know, Refinerycms 4 uses jQuery UI 5, but the master branch ( and the commit you mention ) uses jQuery UI 6.

That's why I suggested in the PR description to create a specific branch `4-0-stable ` ( as you did for previous versions ) and merge this PR in it.

**Comment by parndt** [comment]
Yeah, I've created `4-0-stable` for you, perhaps we should actually release the 4.0.0 gem from it 😅

**Comment by parndt** [comment]
@bricesanchez what do you think about my proposal above? ^ that way we don't merge this commit into master and it retains its jQuery UI version

**Comment by parndt** [comment]
Thanks @shanser and @bricesanchez

**Comment by parndt** [comment]
I'll push a gem with this change in it. I'm a bit dismayed by our changelog, but that can be cleaned up retrospectively. 😬

**Pull request merged**
