### PR TITLE
Fixes #442

### LINKED ISSUE #442: Switch-locale icons should be inline
But now they appear one under the other:

screenshot 2015-06-19 11 29 13

### PR DESCRIPTION
**Pull request by darmenise**

### CODE REVIEW

**Comment by bricesanchez** [comment]
Categories needs update too : https://github.com/refinery/refinerycms-blog/blob/master/app/views/refinery/blog/admin/categories/_category.html.erb#L5-L13

Could you add it and rebase your branch ?

**Comment by parndt** [comment]
@bricesanchez seems like we might have to do it :smile:

**Comment by darmenise** [comment]
I did it (man of little faith 😉 ), or at least I tried, but couldn't test it, because when I run `bundle exec rake refinery:testing:dummy_app` I get this error of a missing file:

```
[...]
Copied migration 20160807193529_create_seo_meta.seo_meta.rb from seo_meta
Copied migration 20160807193530_remove_meta_keywords_from_seo_meta.seo_meta.rb from seo_meta
rake aborted!
LoadError: cannot load such file -- refinery/core/authorisation_manager
/Users/darmenise/dev/rails/Archive/refinerycms-blog/spec/dummy/config/environment.rb:5:in `<top (required)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
** Invoke refinery:testing:setup_extension (first_time)
** Execute refinery:testing:setup_extension
** Invoke refinery:testing:init_test_database (first_time)
** Execute refinery:testing:init_test_database
rake aborted!
LoadError: cannot load such file -- refinery/core/authorisation_manager
/Users/darmenise/dev/rails/Archive/refinerycms-blog/spec/dummy/config/environment.rb:5:in `<top (required)>'
/Users/darmenise/.rbenv/versions/2.2.2/bin/bundle:23:in `load'
/Users/darmenise/.rbenv/versions/2.2.2/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
** Execute refinery:testing:create_dummy_app
** Execute refinery:testing:dummy_app
```

**Comment by NicholasKirchner** [comment]
Looks like the build on this is failing right now due to conflicting versions of refinerycms.  Rebasing off master if/when #459 is accepted may fix this PR.

**Comment by bricesanchez** [comment]
I've fixed this bug with f97dd928c333b6d4048707895743a5ae543567f5

Thanks all!

**Pull request closed without merging**
