### PR TITLE
Removing old blog custom style

### PR DESCRIPTION
**Pull request by mhtremblay**
Old and new style was overlapping.

### CODE REVIEW

**Comment by parndt** [comment]
Thanks! Are you able to post a screenshot for before/after? This allows us to have good history for CSS changes.

**Comment by mhtremblay** [comment]
screen-shot-2015-05-04-at-8 54 17-am
screen-shot-2015-05-04-at-8 49 52-am

**Comment by parndt** [comment]
Let me know when this is ready and I'll tidy up the commits and merge. Thanks!

**Comment by mhtremblay** [comment]
For my part it's ok, I don't know about @anitagraham .

**Comment by parndt** [comment]
Replaced by #438

**Pull request closed without merging**
